sudo: required

branch:
  only:
    - master

env:
  global:
    - IMG_VERS=$(git rev-parse HEAD)

services:
  - docker

before_install:
  # Build docker image server test
  - docker build -t jamese/chat-server-test ./server/.

script:
  # Run server unit tests
  - docker run jamese/chat-server-test go test -v ./...

after_success:
  # Build docker images
  - docker build -t jamese/chat-server:latest -t jamese/chat-server:$IMG_VERS ./server/.
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push latest images to docker hub
  - docker push jamese/chat-server:latest
  # Push unique images to docker hub
  - docker push jamese/chat-server:$IMG_VERS