version: '3'

services:
  server:
    build:
      context: .
      dockerfile: 'Dockerfile'
    volumes:
      - /app/chat-server/bin
      - ./:/app/chat-server
    ports:
      - 50051:50051
    container_name: chat-server